## NumPy 실습문제

1. 0으로 채워진 크기가 20인 배열을 생성하세요. 

In [3]:
import numpy as np
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

2. 0부터 15까지의 값을 갖는 4 x 4 행렬을 생성하세요. 

In [5]:
np.arange(0,16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

3. 길이가 10인데 세번째 요소만 1이고, 나머지 요소는 0인 배열을 생성하세요.

In [6]:
arr = np.zeros(10)
arr[2] = 1 
arr

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

4. 1에서 10까지의 값을 갖는 배열을 생성하세요.

In [14]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

5. 위의 배열의 순서를 거꾸로 바꿔주세요. 

In [15]:
arr2 = arr[::-1]
arr2

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

6. 4x4 단위행렬을 만드세요. (단위 행렬(영어: identity matrix)은 주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각 행렬이다.)

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

7. 랜덤한 값을 가지는 3X3X3 배열을 생성하세요. 

In [19]:
arr = np.random.rand(27).reshape(3,3,3)
arr

array([[[0.66818695, 0.76248978, 0.32473844],
        [0.51725678, 0.33564621, 0.27154601],
        [0.81001633, 0.23145513, 0.3376256 ]],

       [[0.68065639, 0.86286984, 0.70573589],
        [0.96493929, 0.94548914, 0.61036235],
        [0.08374842, 0.05004277, 0.11792907]],

       [[0.55473354, 0.01413643, 0.79830253],
        [0.41174195, 0.15015329, 0.99033767],
        [0.6195449 , 0.94522878, 0.43879452]]])

8. 위에서 생성한 배열 원소의 최대값, 최솟값을 구하세요. 

In [21]:
print(arr.max())
print(arr.min())

0.9903376663927309
0.014136427872600388


9. 20개의 랜덤한 값을 가진 배열을 생성하고, 그 배열의 평균값을 구하시오.  
    참고: numpy에서 평균을 구하는 함수 - mean() 

In [23]:
np.random.rand(20).mean()

0.44496212689265563

10. 4x4 의 2차원 배열을 생성하세요. 단 테두리는 1을 내부는 0으로 채워주세요. 

In [27]:
arr = np.ones((4,4))
arr[1:3,1:3]= 0 
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])