2020.07.23

# 데이터 분석을 위한 패키지

## 배열 데이터를 효과적으로 다루는 Numpy
### [numpy](https://numpy.org/)
- 파이썬으로 과학 연산을 쉽고 빠르게 할 수 있게 만든 패키지

In [1]:
import numpy as np

#### 시퀀스 데이터를 이용한 배열 생성 - ndarray

In [2]:
data1 = [1,2,3,4,5,6]
arr1 = np.array(data1)
print(type(arr1))
arr1

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6])

In [3]:
data2 = [[1,2,3],[4,5,6]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
data3 = [1.2, 2.3, 3.3]
arr3 = np.array(data3)
arr3

array([1.2, 2.3, 3.3])

In [5]:
arr1.dtype

dtype('int32')

In [6]:
arr3.dtype

dtype('float64')

In [7]:
data4 = [1,2,3.0,4,5]
arr4 = np.array(data4)

In [8]:
arr4.dtype

dtype('float64')

In [9]:
np.arange(10) # 0부터 시작해서 10개 , 값이 하나만 들어가면 개수

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- Data type 설정 가능

In [11]:
np.arange(1,10,2,dtype='float')

array([1., 3., 5., 7., 9.])

- arange 값의 갯수와 reshape 의 값의 수가 맞아야 함. ex) 6 = 2*3

In [12]:
arr5 = np.arange(6).reshape(2,3)
print(arr5)
arr5.shape

[[0 1 2]
 [3 4 5]]


(2, 3)

In [13]:
arr1.shape # 속성

(6,)

#### 특별한 형태의 배열 생성

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
'''
Docstring:
zeros(shape, dtype=float, order='C')

Return a new array of given shape and type, filled with zeros.
'''
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((5,3,4)) # 3-D

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.full((3,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

##### Identity matrix (단위행렬) 생성    
- n x n 인 정사각형 행렬에서 주 대각선이 모두 1이고 나머지는 0인 행렬

In [20]:
'''
Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.
'''
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
'''
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].
'''
# 그래프 눈금을 구할 때 유용함, 균등한 인터벌로 나누어 리턴함. 
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [22]:
data6 = ['1','2','3']
arr6 = np.array(data6)
arr6


array(['1', '2', '3'], dtype='<U1')

- `dtype='<U8'` 의 의미는 Numpy 데이터 형식이 유니코드이며 문자의 수는 최대 8개 라는 것을 의미함.(대문자 U)

#### nparray.astype('data type') 함수를 이용하여 형변환하기

In [23]:
arr6_num = arr6.astype(int)
arr6_num.dtype

dtype('int32')

In [24]:
arr6_num

array([1, 2, 3])

`random` 모듈의 `rand()` - 0~1 사이의 값으로 ndarray 생성 (0 포함, 1 불포함)

In [28]:
np.random.rand(4,5,3) # parameter 은 shape

array([[[0.90887475, 0.63328689, 0.13822579],
        [0.83165909, 0.35920246, 0.12390493],
        [0.55896402, 0.77872222, 0.209804  ],
        [0.47616047, 0.15315952, 0.37430331],
        [0.27952469, 0.33872345, 0.74595647]],

       [[0.07391477, 0.24054502, 0.80984491],
        [0.73799068, 0.65048918, 0.4654517 ],
        [0.15975791, 0.12523335, 0.19958206],
        [0.01370712, 0.02671293, 0.39236036],
        [0.87877521, 0.65254796, 0.5843196 ]],

       [[0.14390704, 0.13965   , 0.58292427],
        [0.23544811, 0.08215384, 0.87067114],
        [0.74822212, 0.3524927 , 0.42681971],
        [0.97330036, 0.31211544, 0.24879195],
        [0.87658432, 0.61412304, 0.22853332]],

       [[0.30651468, 0.59798352, 0.14971816],
        [0.07381141, 0.81642962, 0.95908133],
        [0.68637606, 0.80851109, 0.08819028],
        [0.71403686, 0.60037655, 0.48631786],
        [0.90339924, 0.22695304, 0.24446007]]])

In [29]:
np.random.rand(4,) # parameter 은 shape

array([0.03802168, 0.17325848, 0.24298905, 0.41050887])

In [30]:
np.random.randn(4)

array([ 0.86196456, -0.09127146, -1.2889438 , -0.01714054])

In [32]:
np.random.randint(1,100,size=5)

array([30, 43, 25, 34, 77])

In [33]:
np.random.randint(1,100,size=(3,5))

array([[89, 22, 67, 48, 20],
       [10,  4, 85, 57, 44],
       [73,  5, 77, 93, 31]])

In [36]:
# seed - 랜덤한 값을 동일하게 다시 생성
np.random.seed(23)
np.random.randn(3,4)

array([[ 0.66698806,  0.02581308, -0.77761941,  0.94863382],
       [ 0.70167179, -1.05108156, -0.36754812, -1.13745969],
       [-1.32214752,  1.77225828, -0.34745899,  0.67014016]])

In [38]:
sample_data = np.array([10, 20, 30, 40,50])
np.random.choice(sample_data,size = (2,3))

array([[30, 20, 40],
       [20, 40, 50]])

choice : 정수가 주어지면 np.arange(정수)로 간주함.
```
choice(a, size=None, replace=True, p=None)

Generates a random sample from a given 1-D array
```

In [41]:
np.random.choice(100, size=(4,5), replace = False) # replace default로 True - 중복 허용

array([[79,  5, 19, 54, 44],
       [39, 14, 51, 16, 48],
       [43, 28, 27, 83, 15],
       [58, 96,  7, 95, 90]])

In [51]:
np.random.uniform(size = (3,4)) # 0~1 사이 uniform distribution(연속 균등 분포)

array([[0.44688747, 0.71190753, 0.77365206, 0.5773534 ],
       [0.42504292, 0.6431767 , 0.95174463, 0.87472208],
       [0.08233112, 0.65586079, 0.23849045, 0.66428734]])

In [52]:
np.random.normal(size=(3,4)) # a normal (Gaussian) distribution(정규 분포)

array([[ 0.10676019,  0.63520796, -0.63150823, -1.47837884],
       [-0.71291184,  0.04901443,  1.46241896, -0.08177   ],
       [-0.17975747, -0.15909608, -0.2654266 , -1.00253666]])

In [53]:
np.random.randn(3,4) # "standard normal" distribution(표준 정규 분포)

array([[-0.37652165, -0.09984724,  0.92925701,  0.83538646],
       [ 2.07428434, -0.63017078,  0.04649274,  0.23220144],
       [ 0.22327864, -0.76843208, -0.18954254, -1.10881976]])

###  배열의 연산

In [54]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

arr1+arr2

array([11, 22, 33, 44])

In [57]:
arr3 = np.arange(15).reshape(3,5) # arange ndarray -> ndarray    "method chaining"
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
type(arr3)

numpy.ndarray