2020.07.24
### Pandas 기초 실습
1. read_csv() 파일 읽기
    - header 옵션
    - delimiter 옵션
2. head(). tail()을 이용한 간단한 DataFrame 조회
3. pandas.Series() 객체 
    - 생성
    - 다양한 속성
        - shape
        - size
    - 다양한 함수
        - mean()
        - value_counts()
        - count()
    - 연산
    - drop()
    - 조건 필터링
    - 인덱스 접근
4. DataFrame 생성 및 파일로 저장하기
    - dictinary list로 부터 DataFrame생성 :`pandas.DataFrame()`
    - ndarray로 부터 DataFrame 생성 : `pandas.DataFrame.from_records()`
    -  csv 파일로 저장 : `pandas.DataFrame.to_csv()`
    

### read_csv() 파일 읽기

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('pandas_data\\student.csv')
df

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
type(df.이름)

pandas.core.series.Series

In [5]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.0
pytest: 3.5.1
pip: 20.1
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: 0.9.2
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None


In [6]:
df.head() # default 5개 

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

In [7]:
df.tail()

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

In [8]:
df.head(n=2)

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동

In [9]:
df.tail(1) 

이름  나이           주소
2  개나리  19  서울시 강남구 역삼동

In [10]:
df = pd.read_csv('pandas_data\student_tab.txt')
df

이름\t나이\t주소
0  강경미\t30\t경기도 고양시 일산동구
1   고길동\t20\t서울시 노원구 상계동
2   개나리\t19\t서울시 강남구 역삼동

#### delimiter option

In [11]:
df = pd.read_csv('pandas_data\student_tab.txt',delimiter = '\t')
df

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

In [12]:
df = pd.read_csv('pandas_data\student_data.txt')
df

Unnamed: 0  name  age       address
0           0  kang   30  경기도 고양시 일산동구
1           1   kim   23   서울시 강남구 역삼동
2           2  hong   22    서울시 양천구 목동
3           3   lee   31  서울시 영등포구 양평동
4           4   hhh   27   서울시 노원구 상계동

#### header option

In [13]:
df = pd.read_csv('pandas_data\student_data.txt', header=None)
df

0     1    2             3
0  NaN  name  age       address
1  0.0  kang   30  경기도 고양시 일산동구
2  1.0   kim   23   서울시 강남구 역삼동
3  2.0  hong   22    서울시 양천구 목동
4  3.0   lee   31  서울시 영등포구 양평동
5  4.0   hhh   27   서울시 노원구 상계동

In [14]:
df = pd.read_csv('pandas_data\student_data.txt')
df.columns=['순서','이름','나이','주소']
df

순서    이름  나이            주소
0   0  kang  30  경기도 고양시 일산동구
1   1   kim  23   서울시 강남구 역삼동
2   2  hong  22    서울시 양천구 목동
3   3   lee  31  서울시 영등포구 양평동
4   4   hhh  27   서울시 노원구 상계동

## Series - pandas 가 제공하는 객체
- **`numpy`의 `ndarray`를 기반으로 인덱싱을 추가한 1차원 배열**
- 인덱스를 지정하지 않으면, 기본적으로 ndarray와 같이 -부터 시작하는 인덱스를 생성, 지정할 경우 명시적으로 지정된 index를 사용
- 같은 타입의 0개 이상의 데이터를 가질 수 있다.


https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html

In [15]:
# series 생성
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [16]:
pd.Series(['a','b','c'])

0    a
1    b
2    c
dtype: object

In [17]:
import numpy as np
s = pd.Series(np.arange(100)).head()

In [18]:
s

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [19]:
#  pd.Series(data, index)
pd.Series([1,2,3],[100,200,300])

100    1
200    2
300    3
dtype: int64

In [20]:
pd.Series([1,2,3],['a','b','c'])

a    1
b    2
c    3
dtype: int64

In [21]:
s2 = pd.Series([1,2,3],['a','b','c'],dtype=np.int16)
s2

a    1
b    2
c    3
dtype: int16

In [22]:
s2.index

Index(['a', 'b', 'c'], dtype='object')

In [23]:
s2.values

array([1, 2, 3], dtype=int16)

In [24]:
s_name = df.이름
s_name # Serise type

0    kang
1     kim
2    hong
3     lee
4     hhh
Name: 이름, dtype: object

In [25]:
s_name[0]

'kang'

In [26]:
s_name[3] = '박지영'
s_name[3]

C:\Users\Hwang\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


'박지영'

In [27]:
s_name.loc[3]

'박지영'

In [28]:
s_name

0    kang
1     kim
2    hong
3     박지영
4     hhh
Name: 이름, dtype: object

In [29]:
s_name[2]='손채연'
s_name

C:\Users\Hwang\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


0    kang
1     kim
2     손채연
3     박지영
4     hhh
Name: 이름, dtype: object

In [30]:
s = pd.Series([1,2,1,1,24,4,3,2,4,4,5,np.NaN])
s

0      1.0
1      2.0
2      1.0
3      1.0
4     24.0
5      4.0
6      3.0
7      2.0
8      4.0
9      4.0
10     5.0
11     NaN
dtype: float64

In [31]:
len(s)

12

In [32]:
s.size

12

In [33]:
s.shape

(12,)

#### unique()
- Return unique values of Series object.

In [34]:
s.unique()

array([ 1.,  2., 24.,  4.,  3.,  5., nan])

In [35]:
s.count()

11

In [36]:
arr = np.array([3,3,3,np.NaN])
arr

array([ 3.,  3.,  3., nan])

In [37]:
arr.mean()

nan

In [38]:
s2 = pd.Series(arr)
s2

0    3.0
1    3.0
2    3.0
3    NaN
dtype: float64

In [39]:
s2.mean()

3.0

### Series.value_counts()

In [40]:
s

0      1.0
1      2.0
2      1.0
3      1.0
4     24.0
5      4.0
6      3.0
7      2.0
8      4.0
9      4.0
10     5.0
11     NaN
dtype: float64

In [41]:
s.value_counts()

4.0     3
1.0     3
2.0     2
5.0     1
3.0     1
24.0    1
dtype: int64

In [42]:
s[2]

1.0

In [43]:
s[[2,7]].values

array([1., 2.])

In [44]:
s[[2,7]].value_counts()

2.0    1
1.0    1
dtype: int64

### 연산

In [45]:
s1 = pd.Series([1,2,3,4], ['a','b','c','d'])
s2 = pd.Series([6,2,5,3],['d','c','b','a'])

In [46]:
s1

a    1
b    2
c    3
d    4
dtype: int64

In [47]:
s2

d    6
c    2
b    5
a    3
dtype: int64

In [48]:
#인덱스 기준 연산
s1+s2

a     4
b     7
c     5
d    10
dtype: int64

In [49]:
print(s1)
# 산술연산
s1**2

a    1
b    2
c    3
d    4
dtype: int64


a     1
b     4
c     9
d    16
dtype: int64

In [50]:
s1 ** s2

a       1
b      32
c       9
d    4096
dtype: int64

- 인덱스 짝이 맞지 않을 경우 결과는 NaN

In [51]:
s1['e'] = 9
s2['k'] = 20

In [52]:
s1

a    1
b    2
c    3
d    4
e    9
dtype: int64

In [53]:
s2

d     6
c     2
b     5
a     3
k    20
dtype: int64

In [54]:
s1+s2

a     4.0
b     7.0
c     5.0
d    10.0
e     NaN
k     NaN
dtype: float64

In [55]:
s3 = pd.Series(np.arange(10),np.arange(10)+1)

In [56]:
s3

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [57]:
# Boolean 연산 
s3>5

1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
dtype: bool

### Serise[condition]

In [58]:
s4 = s3[s3>5]
s4

7     6
8     7
9     8
10    9
dtype: int32

In [59]:
s3

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [60]:
s5 = s3[s3%2==0]
s5

1    0
3    2
5    4
7    6
9    8
dtype: int32

In [61]:
s3.index>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [62]:
s6 = s3[s3.index>5]
s6

6     5
7     6
8     7
9     8
10    9
dtype: int32

In [63]:
s6 = s3[(s3>3) & (s3<8)]
s6

5    4
6    5
7    6
8    7
dtype: int32

In [64]:
s3

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [65]:
(s3>7).sum() # True + True = 1+1

2

In [66]:
s3[s3>7].sum() # 8 + 9

17

In [67]:
s = pd.Series(np.arange(100,105),['a','b','c','d','e'])
s

a    100
b    101
c    102
d    103
e    104
dtype: int32

In [68]:
s['a'] = 200
s

a    200
b    101
c    102
d    103
e    104
dtype: int32

In [69]:
s['f'] = 105
s

a    200
b    101
c    102
d    103
e    104
f    105
dtype: int64

#### Series.drop()

In [70]:
ss = s.drop('a')
ss

b    101
c    102
d    103
e    104
f    105
dtype: int64

#### inplace 옵션 (default = False)
- False이면 원본 DataFrame은 직접적으로 drop을 적용하지 않으며 원본 DataFrame에서 데이터가 drop된 새로운 DataFrame을 반환한다.
- True이면 해당 내용을 직접 반영한다.

In [71]:
s.drop('f',inplace = True)
s

a    200
b    101
c    102
d    103
e    104
dtype: int64

In [72]:
s

a    200
b    101
c    102
d    103
e    104
dtype: int64

###  인덱스 여러 개에 접근

In [73]:
s[['a','b']] = [10, 20]
s

a     10
b     20
c    102
d    103
e    104
dtype: int64

In [74]:
s[1:3]

b     20
c    102
dtype: int64

In [75]:
s['a':'c']

a     10
b     20
c    102
dtype: int64

###  DataFrame 생성 및 파일로 저장하기
#### dictionary list 로 부터 DataFrame생성 : `pandas.DataFrame()`

In [76]:
import pandas as pd
student_dict_list = [
    {'name':'kang','age':30,'address':'경기도 고양시 일산동구'},
    {'name':'kim','age':23,'address':'서울시 강남구 역삼동'},
    {'name':'hong','age':22,'address':'서울시 양천구 목동'},
    {'name':'lee','age':31,'address':'서울시 영등포구 양평동'},
    {'name':'hhh','age':27,'address':'서울시 노원구 상계동'}    
]

df = pd.DataFrame(student_dict_list)
df

address  age  name
0  경기도 고양시 일산동구   30  kang
1   서울시 강남구 역삼동   23   kim
2    서울시 양천구 목동   22  hong
3  서울시 영등포구 양평동   31   lee
4   서울시 노원구 상계동   27   hhh

In [77]:
df[['age','name','address']]

age  name       address
0   30  kang  경기도 고양시 일산동구
1   23   kim   서울시 강남구 역삼동
2   22  hong    서울시 양천구 목동
3   31   lee  서울시 영등포구 양평동
4   27   hhh   서울시 노원구 상계동

In [78]:
df.head()

address  age  name
0  경기도 고양시 일산동구   30  kang
1   서울시 강남구 역삼동   23   kim
2    서울시 양천구 목동   22  hong
3  서울시 영등포구 양평동   31   lee
4   서울시 노원구 상계동   27   hhh

#### ndarray로 부터 DataFrame 생성 : `pandas.DataFrame.from_records()`

In [79]:
student_list = [
    ['carami',30, None],
    ['kim',20,'고양시'],
    ['hong',33,'서울시'],
    ['lee',24,'광주시'],
    ['kang',30,'대전시'],
]
colum_list = ['name','age','address']
df = pd.DataFrame.from_records(student_list,columns=colum_list)
df

name  age address
0  carami   30    None
1     kim   20     고양시
2    hong   33     서울시
3     lee   24     광주시
4    kang   30     대전시

#### csv 파일로 저장 : `pandas.DataFrame.to_csv()`
- na_rep 옵션 : string, default '' Missing data representation , 결측값을 대체 문자 설정

##### Inf와 NaN
- NumPy에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.    
    다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.    
    0을 0으로 나누려고 시도하면 np.nan이 나온다.

In [80]:
df.to_csv('student_list.txt',na_rep='_' )

In [81]:
df.to_csv('student_list.csv', index=False, header=False,na_rep='_' )

In [82]:
df.to_csv('student_list.txt',na_rep='_', header=['이름','나이','주소'] )