2020.07.24

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('pandas_data\\student.csv')
df

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
type(df.이름)

pandas.core.series.Series

In [5]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.0
pytest: 3.5.1
pip: 20.1
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: 0.9.2
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None


In [6]:
df.head() # default 5개 

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

In [7]:
df.tail()

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

In [8]:
df.head(n=2)

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동

In [9]:
df.tail(1) 

이름  나이           주소
2  개나리  19  서울시 강남구 역삼동

In [10]:
df = pd.read_csv('pandas_data\student_tab.txt')
df

이름\t나이\t주소
0  강경미\t30\t경기도 고양시 일산동구
1   고길동\t20\t서울시 노원구 상계동
2   개나리\t19\t서울시 강남구 역삼동

#### delimiter option

In [11]:
df = pd.read_csv('pandas_data\student_tab.txt',delimiter = '\t')
df

이름  나이            주소
0  강경미  30  경기도 고양시 일산동구
1  고길동  20   서울시 노원구 상계동
2  개나리  19   서울시 강남구 역삼동

In [12]:
df = pd.read_csv('pandas_data\student_data.txt')
df

Unnamed: 0  name  age       address
0           0  kang   30  경기도 고양시 일산동구
1           1   kim   23   서울시 강남구 역삼동
2           2  hong   22    서울시 양천구 목동
3           3   lee   31  서울시 영등포구 양평동
4           4   hhh   27   서울시 노원구 상계동

#### header option

In [13]:
df = pd.read_csv('pandas_data\student_data.txt', header=None)
df

0     1    2             3
0  NaN  name  age       address
1  0.0  kang   30  경기도 고양시 일산동구
2  1.0   kim   23   서울시 강남구 역삼동
3  2.0  hong   22    서울시 양천구 목동
4  3.0   lee   31  서울시 영등포구 양평동
5  4.0   hhh   27   서울시 노원구 상계동

In [14]:
df = pd.read_csv('pandas_data\student_data.txt')
df.columns=['순서','이름','나이','주소']
df

순서    이름  나이            주소
0   0  kang  30  경기도 고양시 일산동구
1   1   kim  23   서울시 강남구 역삼동
2   2  hong  22    서울시 양천구 목동
3   3   lee  31  서울시 영등포구 양평동
4   4   hhh  27   서울시 노원구 상계동

## Series - pandas 가 제공하는 객체
- **`numpy`의 `ndarray`를 기반으로 인덱싱을 추가한 1차원 배열**
- 인덱스를 지정하지 않으면, 기본적으로 ndarray와 같이 -부터 시작하는 인덱스를 생성, 지정할 경우 명시적으로 지정된 index를 사용
- 같은 타입의 0개 이상의 데이터를 가질 수 있다.


https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html

In [15]:
# series 생성
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [16]:
pd.Series(['a','b','c'])

0    a
1    b
2    c
dtype: object

In [17]:
import numpy as np
s = pd.Series(np.arange(100)).head()

In [18]:
s

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [19]:
#  pd.Series(data, index)
pd.Series([1,2,3],[100,200,300])

100    1
200    2
300    3
dtype: int64

In [20]:
pd.Series([1,2,3],['a','b','c'])

a    1
b    2
c    3
dtype: int64

In [21]:
s2 = pd.Series([1,2,3],['a','b','c'],dtype=np.int16)
s2

a    1
b    2
c    3
dtype: int16

In [22]:
s2.index

Index(['a', 'b', 'c'], dtype='object')

In [23]:
s2.values

array([1, 2, 3], dtype=int16)

In [25]:
s_name = df.이름
s_name # Serise type

0    kang
1     kim
2    hong
3     lee
4     hhh
Name: 이름, dtype: object

In [26]:
s_name[0]

'kang'

In [27]:
s_name[3] = '박지영'
s_name[3]

C:\Users\Hwang\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


'박지영'

In [28]:
s_name.loc[3]

'박지영'

In [29]:
s_name

0    kang
1     kim
2    hong
3     박지영
4     hhh
Name: 이름, dtype: object

In [30]:
s_name[2]='손채연'
s_name

C:\Users\Hwang\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


0    kang
1     kim
2     손채연
3     박지영
4     hhh
Name: 이름, dtype: object

In [31]:
s = pd.Series([1,2,1,1,24,4,3,2,4,4,5,np.NaN])
s

0      1.0
1      2.0
2      1.0
3      1.0
4     24.0
5      4.0
6      3.0
7      2.0
8      4.0
9      4.0
10     5.0
11     NaN
dtype: float64

In [32]:
len(s)

12

In [33]:
s.size

12

In [34]:
s.shape

(12,)

#### unique()
- Return unique values of Series object.

In [35]:
s.unique()

array([ 1.,  2., 24.,  4.,  3.,  5., nan])

In [36]:
s.count()

11

In [37]:
arr = np.array([3,3,3,np.NaN])
arr

array([ 3.,  3.,  3., nan])

In [38]:
arr.mean()

nan

In [39]:
s2 = pd.Series(arr)
s2

0    3.0
1    3.0
2    3.0
3    NaN
dtype: float64

In [40]:
s2.mean()

3.0

### Series.value_counts()

In [44]:
s

0      1.0
1      2.0
2      1.0
3      1.0
4     24.0
5      4.0
6      3.0
7      2.0
8      4.0
9      4.0
10     5.0
11     NaN
dtype: float64

In [41]:
s.value_counts()

4.0     3
1.0     3
2.0     2
5.0     1
3.0     1
24.0    1
dtype: int64

In [42]:
s[2]

1.0

In [48]:
s[[2,7]].values

array([1., 2.])

In [49]:
s[[2,7]].value_counts()

2.0    1
1.0    1
dtype: int64

### 연산

In [50]:
s1 = pd.Series([1,2,3,4], ['a','b','c','d'])
s2 = pd.Series([6,2,5,3],['d','c','b','a'])

In [51]:
s1

a    1
b    2
c    3
d    4
dtype: int64

In [52]:
s2

d    6
c    2
b    5
a    3
dtype: int64

In [53]:
#인덱스 기준 연산
s1+s2

a     4
b     7
c     5
d    10
dtype: int64

In [55]:
print(s1)
# 산술연산
s1**2

a    1
b    2
c    3
d    4
dtype: int64


a     1
b     4
c     9
d    16
dtype: int64

In [57]:
s1 ** s2

a       1
b      32
c       9
d    4096
dtype: int64

- 인덱스 짝이 맞지 않을 경우 결과는 NaN

In [58]:
s1['e'] = 9
s2['k'] = 20

In [59]:
s1

a    1
b    2
c    3
d    4
e    9
dtype: int64

In [60]:
s2

d     6
c     2
b     5
a     3
k    20
dtype: int64

In [61]:
s1+s2

a     4.0
b     7.0
c     5.0
d    10.0
e     NaN
k     NaN
dtype: float64

In [62]:
s3 = pd.Series(np.arange(10),np.arange(10)+1)